* -----------------------------------------------------
* XLS2GMS 2.8      40.1.1 23eb37fb Aug 16, 2022          VS8 x86 32bit/MS Window
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     16.0
* Workbook:    https://d.docs.live.net/7ddd391daa881965/Documents/GitHub/JSSP_optimization_project/GAMS/test_data.xlsx
* Sheet:       Sheet2
* Range:       $C$11:$E$14
* -----------------------------------------------------
     1    2   
1    10   6   
2    8    5   
3    12   7   
* -----------------------------------------------------
